Fix gcc error when openmp-dev is not installed.
With libgomp-devel python setup.py gives me this empty gcc warning due to
an empty string arg.

shlomif@telaviv1:~/Download/unpack/prog/python/primesieve-python$ python setup.py bdist
get_compiler_openmp_flag():
running bdist
running bdist_dumb
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/primesieve
copying primesieve/__init__.py -> build/lib.linux-x86_64-2.7/primesieve
creating build/lib.linux-x86_64-2.7/primesieve/numpy
copying primesieve/numpy/__init__.py -> build/lib.linux-x86_64-2.7/primesieve/numpy
running build_ext
building 'primesieve._primesieve' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/primesieve
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -I/usr/include/ncursesw -DNDEBUG -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -g -fPIC -Ilib/primesieve/include -I/usr/include/python2.7 -c primesieve/_primesieve.cpp -o build/temp.linux-x86_64-2.7/primesieve/_primesieve.o
gcc: error: : No such file or directory
error: command 'gcc' failed with exit status 1
shlomif@telaviv1:~/Download/unpack/prog/python/primesieve-python$